sheet_config = {
    "VEICULOS": ("VEICULO", "DESCR_TIPO_VEICULO"),
}

excluded_sheets = {"DICIONÁRIO DE DADOS", "DICIONARIO DE DADOS", "METODOLOGIA"}

adjusted_region_names = {
    'SAO BARBARA D OESTE': "SANTA BARBARA D'OESTE",
    'SAO ANDRE': 'SANTO ANDRE',
    'PALMEIRA D OESTE': "PALMEIRA D'OESTE",
    'SAO ALBERTINA': 'SANTA ALBERTINA',
    'APARECIDA D OESTE': "APARECIDA D'OESTE",
    'SAO GERTRUDES': 'SANTA GERTRUDES',
    'SAO ISABEL': 'SANTA ISABEL',
    'SAO ANTONIO DE POSSE': 'SANTO ANTONIO DE POSSE',
    'SAO ANTONIO DA ALEGRIA': 'SANTO ANTONIO DA ALEGRIA',
    'BIRITIBA-MIRIM': 'BIRITIBA MIRIM',
    'CAMPINA MONTE ALEGRE': 'CAMPINA DO MONTE ALEGRE',
    'SAO ANTONIO DO PINHAL': 'SANTO ANTONIO DO PINHAL',
    'ESPIRITO STO. PINHAL': 'ESPIRITO SANTO DO PINHAL',
    'ESTRELA D OESTE': "ESTRELA D'OESTE",
    'EUCLIDES DA CUNHA PTA': 'EUCLIDES DA CUNHA PAULISTA',
    'FLORINIA': 'FLORINEA',
    'MIRANTE PARANAPANEMA': 'MIRANTE DO PARANAPANEMA',
    'MONTE SANTO DE MINAS': 'MONTE SANTO DE MINAS',
    'SAO ANTONIO DE ARACANGUA': 'SANTO ANTONIO DO ARACANGUA',
    'PIRAPORA BOM JESUS': 'PIRAPORA DO BOM JESUS',
    'SAO ROSA DE VITERBO': 'SANTA ROSA DE VITERBO',
    'SAO CRUZ DA CONCEICAO': 'SANTA CRUZ DA CONCEICAO',
    'SAO ERNESTINA': 'SANTA ERNESTINA',
    'SAO BRANCA': 'SANTA BRANCA',
    'SAO CRUZ DAS PALMEIRAS': 'SANTA CRUZ DAS PALMEIRAS',
    'SAO CRUZ DO RIO PARDO': 'SANTA CRUZ DO RIO PARDO',
    'SAO FE DO SUL': 'SANTA FE DO SUL',
    'SAO LUCIA': 'SANTA LUCIA',
    'SAO ANTONIO DO JARDIM': 'SANTO ANTONIO DO JARDIM',
    'SAO RITA PASSA QUATRO': 'SANTA RITA DO PASSA QUATRO',
    'SAO MERCEDES': 'SANTA MERCEDES',
    'SAO JOAO DUAS PONTES': 'SAO JOAO DAS DUAS PONTES',
    'SAO CRUZ DA ESPERANCA': 'SANTA CRUZ DA ESPERANCA'
}

needed_columns = ['data_ocorrencia_bo', 'nome_delegacia', 'num_bo', 
                  'descr_marca_veiculo', 'descr_tipo', 'descr_ocorrencia_veiculo', 
                  'cidade', 'bairro', 'latitude', 'longitude', 'cod_municipio',
                  'populacao_estimada', 'area_km2']